### ISSUE TITLE
the issues when running under QEMU 6.0.50

### ISSUE THREAD

**Issue by zhang-billy** [zhuowei/XNUQEMUScripts#1]
QEMU 6.0.50 monitor - type 'help' for more information
(qemu) qemu-system-aarch64: Unable to copy device tree in memory
Couldn't open dtb file iOSFiles/devicetree.dtb

I user this version ipws file iPhone10,3,iPhone10,6_12.4_16G5046d_Restore

**Comment by zhuowei** [comment]
Did you [generate](https://github.com/zhuowei/XNUQEMUScripts/blob/master/iOSFiles/README.md) the modified device tree?
```
python3 modifydevicetree.py path/to/ipsw/Firmware/all_flash/DeviceTree.d321ap.im4p devicetree.dtb
```
Note that this code is fairly old: at this point, you're better off using one of the better tools such as Aleph Security's emulator.

**Comment by zhang-billy** [comment]
Yes, I was just following the tutorial from here https://worthdoingbadly.com/xnuqemu2/

Now, I downloaded the tools in here https://github.com/alephsecurity/xnu-qemu-arm64-tools/tree/master/bootstrap_scripts, as you mentioned.

make my device tree.dtb as following :
python3 asn1dtredecode.py DeviceTree.d22ap.im4p devicetree.dtb

but running runqemu is not successful yet

QEMU 6.0.50 monitor - type 'help' for more information
(qemu) qemu-system-aarch64: Unable to copy device tree in memory
Couldn't open dtb file iOSFiles/devicetree.dtb

**Comment by zhang-billy** [comment]
It's successful with Aleph Security's tutors
